### ISSUE TITLE
.NET Framework 4.8 is not supported

### ISSUE THREAD

**Issue by flyrainning** [dme-compunet/YoloSharp#100]
Can the support for .NET Framework 4.8 be added?

**Comment by dme-compunet** [comment]
I don't mess with .NET Framework, but I'm not sure if there's anything else besides changing the `TargetFramework` to `netstandard2.0`, PR would be welcome.

**Comment by dme-compunet** [comment]
ImageSharp does not support .NET Framework, so unfortunately this is not possible.
