### ISSUE TITLE
How to replace yolosharp with yolosharp.gpu？

### ISSUE THREAD

**Issue by April-HAA** [dme-compunet/YoloSharp#101]
I want to load my onnx model using GPU. But after downloading yolosharp-gpu from nuget, an error occurs in the Demo: YoloPredictor exists in both yolosharp and yolosharp.gpu. How to replace yolosharp with yolosharp.gpu？

**Comment by dme-compunet** [comment]
Remove `YoloSharp` package from your project

**Comment by April-HAA** [comment]
Thank you very much for your answer and for your time. I want to use this YoloSharp.Gpu on a Winform project, but I found that the two frameworks are different and cannot be used directly. Can you tell me how to do it?

**Comment by dme-compunet** [comment]
YoloSharp is not compatible with .NET Framework, I don't know if winform is compatible with .NET, if it is, then you should convert your project to .NET

**Comment by April-HAA** [comment]
OK. Thank you very much for your answer and for your time.
