### ISSUE TITLE
Using YoloSharp together with YoloSharpGPU

### ISSUE THREAD

**Issue by RexxNorilsk** [dme-compunet/YoloSharp#102]
Hi, I am faced with the following task - I need to use two modes in the project:
 - GPU detection 
 - Detection by CPU
And be able to switch them at least at the initialization stage. At the moment, I face the problem that class definitions are found in both YoloSharp and YoloSharp.Gpu.

**Comment by dme-compunet** [comment]
Add reference to `YoloSharp.Gpu`, and use it like this:

```csharp
var gpuOptions = new YoloPredictorOptions
{
    UseCuda = true,
};

var cpuOptions = new YoloPredictorOptions
{
    UseCuda = false,
};

using var gpuPredictor = new YoloPredictor("...", gpuOptions);

using var cpuPredictor = new YoloPredictor("...", cpuOptions);
```

**Comment by RexxNorilsk** [comment]
Thanks for answer! It's really working
