### ISSUE TITLE
How to build my own model.

### ISSUE THREAD

**Issue by zydjohnHotmail** [dme-compunet/YoloSharp#104]
Hi, 
I want to make my own models, I have some images with some json format labels in the following folder: 
D:\YOLODOG>dir /w
 Volume in drive D is Local Disk
 Volume Serial Number is CEA9-DFE7

 Directory of D:\YOLODOG

[.]                  GBHARAM_6_001.json   GBHARAM_6_001.png    GBHARAM_6_002.json   GBHARAM_6_002.png
GBHARAM_6_003.json   GBHARAM_6_003.png    GBHARAM_6_004.json   GBHARAM_6_004.png    GBHARAM_6_005.json
GBHARAM_6_005.png    GBHARAM_6_006.json   GBHARAM_6_006.png    GBHARAM_6_007.json   GBHARAM_6_007.png
GBHARAM_6_008.json   GBHARAM_6_008.png    GBHARAM_6_009.json   GBHARAM_6_009.png    GBHARAM_6_010.json
=> The following is my current code:
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Transforms.Image;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Media;
using static YOLODOGTrainForm.DataStructure;

namespace YOLODOGTrainForm
{
    public partial class Form1 : Form
    {

        private static IEnumerable<ImageData> LoadData(List<string> imagePaths)
        {
            foreach (string imagePath in imagePaths)
            {
                // Dummy labels for simplicity (adjust according to your dataset)
                yield return new ImageData
                {
                    ImagePath = imagePath,
                    Label = "0" // Example label
                };
            }
        }

        private static ITransformer CreateDataPrepPipeline(MLContext mlContext, IDataView data)
        {
            var dataPrepPipeline = mlContext.Transforms
            .LoadImages(outputColumnName: "images", imageFolder: "", inputColumnName: nameof(ImageData.ImagePath))
            .Append(mlContext.Transforms.ResizeImages(outputColumnName: "images_resized", imageWidth: 854, imageHeight: 480, inputColumnName: "images"))
            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "images_pixels", inputColumnName: "images_resized"))
            .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "LabelKey", inputColumnName: nameof(ImageData.Label)));

            ITransformer dataPrepTransformer = dataPrepPipeline.Fit(data);
            mlContext.Model.Save(dataPrepTransformer, data.Schema, "data_preparation_pipeline.zip");
            return dataPrepTransformer;
        }

        private static ITransformer TrainModel(MLContext mlContext, IDataView transformedData)
        {
            var modelPipeline = mlContext.Transforms.ApplyOnnxModel(
            modelFile: "D:/YOLODOG/model/yolodog.onnx",
            outputColumnNames: new[] { "output0" },
            inputColumnNames: new[] { "images_pixels" });

            ITransformer trainedModel = modelPipeline.Fit(transformedData);
            mlContext.Model.Save(trainedModel, transformedData.Schema, "model.zip");
            return trainedModel;
        }

        private static void ExportModelToOnnx(MLContext mlContext, ITransformer model, IEnumerable<ImageData> data)
        {
            // Dummy schema to define inputs and outputs
            SchemaDefinition schemaDefinition = 
                SchemaDefinition.Create(typeof(ImageData));
            schemaDefinition[nameof(ImageData.Label)].ColumnType = TextDataViewType.Instance;
            // Export to ONNX
            string onnxPath = @"D:\YOLODOG\model\yolodog.onnx";
            using (FileStream stream = File.Create(onnxPath))
            {
                mlContext.Model.ConvertToOnnx(model, mlContext.Data.LoadFromEnumerable(data), stream);
            }

            Debug.Print($"Model exported to ONNX at {onnxPath}");
            Console.Beep();
            Console.Beep();
        }

        public Form1()
        {
            InitializeComponent();
        }

        private void BTNFinish_Click(object sender, EventArgs e)
        {
            Console.Beep();
            Environment.Exit(0);
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            // Initialize MLContext
            MLContext mlContext = new MLContext();

            // Load data
            List<string> imagePaths = Directory.GetFiles(@"D:\YOLODOG", "*.png").ToList();
            IEnumerable<ImageData> trainingData = LoadData(imagePaths);
            IDataView data = mlContext.Data.LoadFromEnumerable(trainingData);

            // Create and save data preparation pipeline
            ITransformer dataPrepTransformer = CreateDataPrepPipeline(mlContext, data);

            // Transform data using the data preparation pipeline
            IDataView transformedData = dataPrepTransformer.Transform(data);

            // Train and save the model
            ITransformer trainedModel = TrainModel(mlContext, transformedData);

            // Export the trained model to ONNX
            ExportModelToOnnx(mlContext, trainedModel, trainingData);

            // Load the pipelines for prediction (if needed)
            DataViewSchema dataPrepPipelineSchema, modelSchema;
            ITransformer loadedDataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out dataPrepPipelineSchema);
            ITransformer loadedModel = mlContext.Model.Load("model.zip", out modelSchema);

            // Use the loaded pipelines for prediction
            // Example: var predictions = loadedModel.Transform(loadedDataPrepPipeline.Transform(newData));
        }
    }
}
=> When I run my code, I always get the following run time error:
System.IO.IOException
  HResult=0x80131620
  Message=Model file D:/YOLODOG/model/yolodog.onnx does not exists.
  Source=Microsoft.ML.Core
  StackTrace:
   at Microsoft.ML.Runtime.Contracts.CheckIO(IExceptionContext ctx, Boolean f, String msg, Object[] args)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at YOLODOGTrainForm.Form1.TrainModel(MLContext mlContext, IDataView transformedData) in D:\LanguageModels\YOLODOGTrainForm\YOLODOGTrainForm\Form1.cs:line 46
   at YOLODOGTrainForm.Form1.Form1_Load(Object sender, EventArgs e) in D:\LanguageModels\YOLODOGTrainForm\YOLODOGTrainForm\Form1.cs:line 103
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

=> I have no clear idea how to train my own model and export using ONNX format, so later I can use the model in other applications.
Can you tell me how to fix this issue? I am using Visual Studio 2022 version 17.12.3 on Windows 11.
Thanks,

**Comment by dme-compunet** [comment]
You don't need to train the model in ML.NET, the training can be in PyTorch, then you need to export the model to .onnx format and use it with this library.

This is the official documentation:
https://docs.ultralytics.com/modes/train

**Comment by zydjohnHotmail** [comment]
Yes, I know.
But even install Python in Windows and make it working take more time than doing things in C#.  So I think maybe using C# to do this could be easier, as Microsoft already has released all necessary machine learning packages, right

**Comment by dme-compunet** [comment]
In my opinion, it's not a good idea to train the model in C#, and if you have a good reason to train in C#, then this is not the place to file a issue, since this repo is not about training.
