### ISSUE TITLE
How to use GPU？

### ISSUE THREAD

**Issue by ckmstydy** [dme-compunet/YoloSharp#78]
I have installed CUDA=12.2 and cuDNN,=9.3， but I still get errors when loading the model using YoloPredictor（my onnxRuntime version is 1.19.1）：

[ErrorCode:RuntimeException]D:al workl1\slonnxruntimelcorelsessionlprovider bridge ort.cc:1637onnxruntime::ProviderLibrary::Get [ONNXRuntimeError : 1 : FAIL :LoadLibrary failed with error 126 "" when trying to load"D:\OrderTaking\PupilDet-onnx-gpuPupilDetlbin\Debuginet8.0-windcws\runtimes\win-x64\native\onnxruntime providers cuda.dll

![error](https://github.com/user-attachments/assets/97505550-2db0-42df-8a02-e09df7de4a35)
![error2](https://github.com/user-attachments/assets/0293e423-c59e-4596-a4dd-a4ce5e29724d)

`var predictor = new YoloPredictor(“/model/best.onnx”);`

**Comment by ErrorGz** [comment]
I haven't used this code for a while, so I'm concerned my response might be incomplete.
First, you clone the dme-compunet/YoloV8 code into your project, then in the NuGet package manager, uninstall Microsoft.ML.OnnxRuntime and install Microsoft.ML.OnnxRuntime.Gpu.
![微信图片_20241009000404](https://github.com/user-attachments/assets/77b1c4cb-7122-4b6b-ad9a-ccf23d26dd8e)

Second, add the zlibwapi.dll file to your project and set it to 'Copy to Output Directory'.
![微信图片_20241009000415](https://github.com/user-attachments/assets/93f87a52-4ee9-4c19-9230-9f9276bd347b)

Third, when you call YoloV8Builder().WithSessionOptions, add parameters with SessionOptions options = new SessionOptions(); and specify options.AppendExecutionProvider_xxxxxxx(). Below is an example using DirectX12, not the GPU example.


```
            SessionOptions options = new SessionOptions();            
            options.AppendExecutionProvider_DML();
            var predictor2 = new YoloV8Builder().WithSessionOptions(options).UseOnnxModel(new BinarySelector("onnx/yolov8n-seg.onnx")).Build();
            return predictor2;"
```

**Comment by dme-compunet** [comment]
@ckmstydy Try adding the cuda `bin` folder to `Path` environment variable

**Comment by ckmstydy** [comment]
> I haven't used this code for a while, so I'm concerned my response might be incomplete. First, you clone the dme-compunet/YoloV8 code into your project, then in the NuGet package manager, uninstall Microsoft.ML.OnnxRuntime and install Microsoft.ML.OnnxRuntime.Gpu. ![微信图片_20241009000404](https://private-user-images.githubusercontent.com/32073343/374637502-77b1c4cb-7122-4b6b-ad9a-ccf23d26dd8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA5MzUsIm5iZiI6MTcyODQ2MDYzNSwicGF0aCI6Ii8zMjA3MzM0My8zNzQ2Mzc1MDItNzdiMWM0Y2ItNzEyMi00YjZiLWFkOWEtY2NmMjNkMjZkZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ODMxMGQ2MWNmZWU2YWMxN2QyODBkYzJlNzk0Y2NmMDQyMmYxZmVkY2MyYmJiZTViZDM0NDUxZDdjNzIwNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._0qnFHzi_av5x8Uu_5P3JIf5LQzve8DX73jM1sCaRS8)
> 
> Second, add the zlibwapi.dll file to your project and set it to 'Copy to Output Directory'. ![微信图片_20241009000415](https://private-user-images.githubusercontent.com/32073343/374637547-93f87a52-4ee9-4c19-9230-9f9276bd347b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA5MzUsIm5iZiI6MTcyODQ2MDYzNSwicGF0aCI6Ii8zMjA3MzM0My8zNzQ2Mzc1NDctOTNmODdhNTItNGVlOS00YzE5LTkyMzAtOWY5Mjc2YmQzNDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmY2M5Mjg4NjM1ZDVmMjRjMzQ1ODBlZTBiNTA4YzE0ZmNmYzBiMTJiZjI0NDQ5ODBlMTc3NzU5NWE3NWFkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QR3-vRtOv9G0crqZOdA0-G5FAYRSsDQD8ZY3NWfN3GY)
> 
> Third, when you call YoloV8Builder().WithSessionOptions, add parameters with SessionOptions options = new SessionOptions(); and specify options.AppendExecutionProvider_xxxxxxx(). Below is an example using DirectX12, not the GPU example.
> 
> ```
>             SessionOptions options = new SessionOptions();            
>             options.AppendExecutionProvider_DML();
>             var predictor2 = new YoloV8Builder().WithSessionOptions(options).UseOnnxModel(new BinarySelector("onnx/yolov8n-seg.onnx")).Build();
>             return predictor2;"
> ```

Thanks, but unfortunately it didn't work for me

**Comment by ckmstydy** [comment]
> @ckmstydy Try adding the cuda `bin` folder to `Path` environment variable

Have already added. And “nvcc -V ” works correctly.
![3](https://github.com/user-attachments/assets/b1d7612e-b8d0-4661-84a5-7c73f3316270)

**Comment by dme-compunet** [comment]
This issue has been open for a long time with no progress, so for now I'm closing it.
