### ISSUE TITLE
Yolov8.GPU unable to load self-trained yolov8 model？

### ISSUE THREAD

**Issue by ckmstydy** [dme-compunet/YoloSharp#84]
train myself yolov8 and transform it to onnx，Loading model error：

“The metadata parsing failed, making sure you use an official YOLOv8 model！”

**Comment by ckmstydy** [comment]
When using YOLOv8 on the CPU, loading the same model file does not report this error, and can be used

**Comment by dme-compunet** [comment]
Um strange.. can you specify the inner exception? 
Can you share a model that reproduces the problem?

**Comment by dme-compunet** [comment]
Can you check if this issue is solved in version `5.1.1`?

**Comment by ckmstydy** [comment]
Thanks.
I finally solved this problem by loading the yolov8.yaml file to create the model and then assigning my own trained model weights to it via model.state_dict().
I am confused as to why this error occurs on the GPU, but the CPU can load the model fine in C#.
I will try YOLO.GPU=5.1.1.
